let data = {
    "config": {
        "image_default": "https://s3.amazonaws.com/gt7sp-prod/decal/20/65/90/4684386837524906520_1.png",
        "currency_default": "руб",
        "description": "Отсортировано по приоритету. <br/> Для бронирования писать <a href=\"tg://resolve?domain=karjalainen_mariia\">Марье</a>",
        "show_archived": 1,
    },
    "items": [
        {
            "name": "Кошелёк",
            "price": 80,
            "currency": "€",
            "url": "https://www.instagram.com/p/Cz81Na6Cl7j/",
            "image": "https://scontent-ams4-1.cdninstagram.com/v/t51.2885-15/403823928_3449459465364639_2670848722027646491_n.heic?stp=dst-jpg_e35&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xNDQweDE0NDAuc2RyIn0&_nc_ht=scontent-ams4-1.cdninstagram.com&_nc_cat=103&_nc_ohc=-Zto8UDWtFgAX9ddGCt&edm=ACWDqb8BAAAA&ccb=7-5&ig_cache_key=MzI0MTY5OTgzNjg1MjU2Njg5NQ%3D%3D.2-ccb7-5&oh=00_AfCWqLdaTBfU5crvJ3AtUkO-YCVQcK6RuTfl0bG2gjTiXg&oe=65632694&_nc_sid=ee9879",
        },
        {
            "name": "Зонт",
            "price": 3600,
            "currency": "RSD",
            "url": "https://geekshop.rs/quick-dry-kisobran/",
            "image": "https://geekshop.rs/wp-content/uploads/2021/11/kisobran-za-brzo-susenje-quick-dry-xd-design-3.jpg",
        },
        {
            "name": "Sling рюкзак",
            "price": 5000,
            "currency": "RSD",
            "url": "https://bange.in.rs/bg-7229",
            "image": "https://static.tildacdn.com/tild3239-3762-4537-b265-386333363162/image_2.jpg",
        },
        {
            "name": "Hacker gift",
            "price": 20,
            "currency": "$",
            "tags": ["geek"],
            "url": "https://hacker.gifts/",
            "image": "https://cdn.shopify.com/s/files/1/0013/8539/8385/products/card_1_1024x1024.png",
        },
        {
            "name": "Футболка Outer Wilds: Written in the Stars",
            "price": 32,
            "currency": "$",
            "tags": ["футболки"],
            "url": "https://www.fangamer.com/collections/outer-wilds/products/outer-wilds-shirt-stars",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_OW_written_in_the_stars_shirt_photo1.png?v=1679098777",
            "description": "Размер XL",
        },
        {
            "name": "Футболка Outer Wilds: Into the Wilds",
            "price": 32,
            "currency": "$",
            "tags": ["футболки"],
            "url": "https://www.fangamer.com/collections/outer-wilds/products/outer-wilds-logo-shirt",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_OW_ventures_shirt_photo1.png?v=1679438441",
            "description": "Размер XL",
        },
        {
            "name": "Футболка Hollow Knight: Troupe Master",
            "price": 32,
            "currency": "$",
            "tags": ["футболки"],
            "url": "https://www.fangamer.com/collections/hollow-knight/products/grimm-hollow-knight-shirt",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_HK_troupe_master_shirt_photo1_1024x1024.png?v=1563036118",
            "description": "Размер XL",
        },
        {
            "name": "Футболка Celeste: Sides",
            "price": 32,
            "currency": "$",
            "tags": ["футболки"],
            "url": "https://www.fangamer.com/collections/celeste/products/celeste-cassette-shirt",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_celeste_sides_shirt_photo1_1024x1024.png?v=1580160195",
            "description": "Размер XL",
        },
        {
            "name": "Hollow Knight Pin",
            "price": 10,
            "currency": "$",
            "tags": ["pins"],
            "url": "https://www.fangamer.com/products/hollow-knight-pin",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_HK_wanderer_lapel_main_1024x1024.jpg?v=1541195039"
        },
        {
            "name": "Saw Cleaver Pin",
            "price": 12,
            "currency": "$",
            "tags": ["pins"],
            "url": "https://www.fangamer.com/collections/bloodborne/products/bloodborne-saw-cleaver-pin",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_bloodborne_plain-doll-hand_pin_main_e65bc9c5-8daf-4b52-9072-ee0204c7a389_1024x1024.png?v=1592247200"
        },

        
        {
            "name": "Настольная игра Spirit Island",
            "price": 12500,
            "currency": "RSD",
            "tags": ["настолки"],
            "url": "https://conflux.rs/index.php?route=product/product&product_id=5643",
            "image": "https://conflux.rs/image/cache/catalog/BoardGameImgs/bg0162886-1100x1100.jpg",
            "archived": 1,
        },
        {
            "name": "Нарды (длинные)",
            "price": 5000,
            "currency": "RSD",
            "tags": ["настолки"],
            "url": "https://ananas.rs/proizvod/komplet-sah-i-bekgemon/540362",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Backgammon_board.jpg/548px-Backgammon_board.jpg",
            "archived": 1,
        },
        {
            "name": "Шахматы",
            "price": 3000,
            "currency": "RSD",
            "tags": ["настолки"],
            "url": "",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Opening_chess_position_from_black_side.jpg/548px-Opening_chess_position_from_black_side.jpg",
            "archived": 1,
        },
        {
            "name": "PlayStation VR2",
            "price": 600,
            "currency": "€",
            "tags": ["техника"],
            "url": "https://www.playstation.com/en-us/ps-vr2/",
            "image": "https://media.direct.playstation.com/is/image/sierialto/PS-VR2-Hero?$Column_Large$",
            "archived": 1,
        },
        {
            "name": "SSD - Samsung 2TB 980 PRO with Heatsink",
            "price": 300,
            "currency": "€",
            "tags": ["техника"],
            "url": "https://www.samsung.com/us/computing/memory-storage/solid-state-drives/980-pro-w-heatsink-pcie-4-0-nvme-ssd-2tb-mz-v8p2t0cw/",
            "image": "https://image-us.samsung.com/SamsungUS/home/92121/dve53bb8700ta3/pc/MZ-V8P2T0CW_01.jpg",
            "archived": 1,
        },
        {
            "name": "The Legend of Zelda: Tears of the Kingdom",
            "price": 70,
            "currency": "€",
            "tags": ["игры"],
            "url": "https://www.nintendo.com/store/products/the-legend-of-zelda-tears-of-the-kingdom-switch/",
            "image": "https://www.games.rs/files/thumbs/files/images/product/thumbs_960/Switch-The-Legend-of-Zelda-Tears-of-The-Kingdom_960_1200px.jpg.webp",
            "archived": 1,
        },
        {
            "name": "Комикс Preacher (Hardcover) Book Four и последующие",
            "price": 27,
            "currency": "$",
            "tags": ["комиксы"],
            "url": "https://www.amazon.com/Preacher-Book-Four-Garth-Ennis/dp/1401230938",
            "image": "https://cdn1.ozone.ru/multimedia/1010438854.jpg",
            "archived": 1,
        },
        {
            "name": "Сертификат от Валеры",
            "price": "5к to infinity and beyond",
            "currency": "(руб)",
            "image": "tattoo-cert.jpg",
            "tags": ["тату", "сертификаты"],
            "url": "https://www.instagram.com/valera_fedya/",
            "multi": 1,
            "archived": 1,
        },
        {
            "name": "Kirby and the Forgotten Land",
            "price": 5000,
            "tags": ["игры"],
            "url": "https://www.avito.ru/moskva?cd=1&q=kirby+forgotten+land",
            "image": "https://www.gamesonly.at/manuelle_artikel_images/Kirby_and_the_Forgotten_Land_Nintendo_Switch_2022_01_07_12_58_20_600.jpg",
            "archived": 1,
        },
        {
            "name": "Яндекс Станция Мини, серая",
            "price": 6000,
            "tags": ["техника"],
            "url": "https://market.yandex.ru/product--umnaia-kolonka-yandex-novaia-stantsiia-mini-bez-chasov-umnaia-kolonka-s-alisoi/1423994419",
            "image": "https://avatars.mds.yandex.net/get-mpic/5318100/img_id3322670545016135840.jpeg/orig",
            "archived": 1,
        },
        {
            "name": "Подарочный сертификат Спорт-Марафон",
            "price": "3000 - 20000",
            "tags": ["сертификаты", "одежда"],
            "url": "https://sport-marafon.ru/catalog/podarochnye-sertifikaty/",
            "image": "https://sport-marafon.ru/upload/resize_cache/files/iblock/elements/757d49da-9fe4-11e1-b026-e83935202583/d5e05e03-19fd-11ec-80cf-901b0e95a2a8/570_550_1/d5e05e0319fd11ec80cf901b0e95a2a8_f3d184b51aee11ec80cf901b0e95a2a8.jpg",
            "multi": 1,
            "archived": 1,
        },
        {
            "name": "Leatherman Free P2",
            "price": 16000,
            "tags": ["инструменты"],
            "url": "https://ileatherman.ru/multitul-leatherman-free-p2-832638-s-nejlonovym-chexlom",
            "image": "https://ileatherman.ru/image/cache/catalog/Produkts2/multitul-leatherman-charge-free-p2-s-nejlonovym-chexlom0-680x680.webp",
            "description": "Или аналогичный",
            "archived": 1,
        },
        {
            "name": "Xiaomi Mijia Electric Precision Screwdriver",
            "price": 3500,
            "tags": ["инструменты"],
            "url": "https://www.ozon.ru/product/elektricheskaya-otvertka-xiaomi-mijia-electric-precision-screwdriver-24v1-mjddlsd003qw-temno-seraya-212879559",
            "image": "https://cdn1.ozone.ru/s3/multimedia-c/wc1000/6029937972.jpg",
            "archived": 1,
        },
        {
            "name": "JBL Charge 5",
            "price": 14000,
            "tags": ["техника"],
            "url": "https://www.mvideo.ru/products/besprovodnaya-akustika-jbl-charge-5-teal-10026198",
            "image": "https://img.mvideo.ru/Big/10026198bb.jpg",
            "archived": 1,
        },
        {
            "name": "Настольная игра 'Покорение марса: Колонии'",
            "price": 2150,
            "tags": ["настолки"],
            "url": "https://hobbygames.ru/pokorenie-marsa-kolonii",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Pokorenie_Marsa/Colonies/pokoreniemarsa-1024x1024-wm.jpg",
            "archived": 1,
        },
        {
            "name": "Дюна. Иллюстрированная история создания классики научной фантастики",
            "price": 4500,
            "tags": ["артбуки"],
            "url": "https://eksmo.ru/book/dyuna-illyustrirovannaya-istoriya-sozdaniya-klassiki-nauchnoy-fantastiki-ITD1177428/",
            "image": "https://cdn.eksmo.ru/v2/ITD000000001177428/COVER/cover1__w820.jpg",
            "archived": 1,
        },
        {
            "name": "Настольная игра 'Немезида'",
            "price": 14000,
            "tags": ["настолки"],
            "url": "https://hobbygames.ru/nemezida",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/HobbyWorld/Nemesis/HG/Nemesis_01-1024x1024-wm.jpg",
            "archived": 1,
        },
        {
            "name": "Apple AirPods Pro",
            "price": 25000,
            "tags": ["техника"],
            "url": "https://www.mvideo.ru/products/naushniki-apple-airpods-pro-with-magsafe-case-mlwk3ru-a-50165904",
            "image": "https://img.mvideo.ru/Big/50165904bb.jpg",
            "archived": 1,
        },
        {
            "name": "Наушники Sony WH-1000XM4",
            "price": 30000,
            "tags": ["техника"],
            "url": "https://store.sony.ru/product/naushniki-sony-wh-1000xm4-317432/",
            "image": "https://store.sony.ru/common/img/catalogue/317432/5d02da5df552836db894cead8a68f5f3-big.png",
            "archived" : 1,
        },
        {
            "name": "Виски Oban malt 14 years old",
            "price": 6500,
            "tags": ["алкоголь"],
            "url": "https://winestyle.ru/products/Oban-malt-14-years-old-with-box.html",
            "image": "https://skygarden.azureedge.net/media/images/products/2019/02/product_image_66b99a62-658d-4018-a8ea-998a174b0231.jpg",
            "archived": 1,
        },
        {
            "name": "New Super Mario Bros U Deluxe",
            "price": 3800,
            "tags": ["игры", "switch"],
            "url": "https://www.mvideo.ru/products/igra-nintendo-switch-new-super-mario-bros-u-deluxe-40070863",
            "image": "https://img.mvideo.ru/Pdb/40070863b.jpg",
            "archived": 1,
        },
        {
            "name": 'Настольная игра «Покорение Марса»',
            "price": 4000,
            "tags": ["настолки"],
            "url": "https://hobbygames.ru/pokorenie-marsa",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Pokorenie_Marsa/Proekt_Venera/Pokorenie_Marsa-1024x1024-wm.jpg",
            "archived": 1,
        },
        {
            "name": "Настольная игра 'Покорение марса: Кризис'",
            "price": 2300,
            "tags": ["настолки"],
            "url": "https://hobbygames.ru/pokorenie-marsa-krizis",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Pokorenie_Marsa/Krizis/Pokorenie_Marsa_Krizis-1024x1024-wm.jpg",
            "archived": 1,
        },
        {
            "name": "Настольная игра 'Покорение марса: Эллада и Элизий'",
            "price": 1250,
            "tags": ["настолки"],
            "url": "https://hobbygames.ru/pokorenie-marsa-jellada-i-jelizij",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Pokorenie_Marsa/Proekt_Venera/Pokorenie_Marsa_Ellada_i_Eliziy-1024x1024-wm.jpg",
            "archived": 1,
        },
        {
            "name": "The Legend of Zelda: Link's Awakening",
            "price": 3800,
            "tags": ["игры", "switch"],
            "url": "https://www.mvideo.ru/products/igra-nintendo-switch-the-legend-of-zelda-link-s-awakening-40071643",
            "image": "https://img.mvideo.ru/Pdb/40071643b.jpg",
            "archived": 1
        },
        {
            "name": "Lego R2-D2 (75308)",
            "price": 19000,
            "tags": ["lego"],
            "url": "https://mir-kubikov.ru/lego/75308/",
            "image": "https://static.mir-kubikov.ru/upload/resize_cache/iblock/e62/746_580_140cd750bba9870f18aada2478b24840a/e6257684e6a453030f0a2516be8e56c6.jpg",
            "archived": 1
        },
        {
            "name": "DOOM. Как в битвах с демонами закалялся новый жанр",
            "price": 655,
            "tags": ["книги"],
            "url": "https://book24.ru/product/doom-kak-v-bitvakh-s-demonami-zakalyalsya-novyy-zhanr-5907841/",
            "image": "https://cdn.book24.ru/v2/ITD000000001110467/COVER/cover3d1__w337.webp",
            "archived": 1
        },
        {
            "name": "Дарт Вейдер. Тёмный повелитель ситхов (Чарльз Соул)",
            "price": 2050,
            "tags": ["комиксы"],
            "url": "https://www.chookandgeek.ru/product/dart-veyder-tyomnyy-povelitel-sithov",
            "image": "https://static-sl.insales.ru/images/products/1/5169/382735409/large_1.jpg",
            "archived": 1
        },
        {
            "name": "Звёздные Войны. Дарт Вейдер. Полное издание (Кирон Гиллен)",
            "price": 1750,
            "tags": ["комиксы"],
            "url": "https://www.respublica.ru/knigi/hudozhestvennaya-literatura/komiksy-i-manga/515545-gillen-k-zvyozdnye-voyny-dart-veyder-polnoe-izdanie-zvezdnye-voyny-dart-veyder-t-o",
            "image": "https://www.respublica.ru/uploads/01/00/00/c3/4l/large_851bd1a5a53f2750.jpg",
            "archived": 1
        },
           {
            "name": "Техносвященники. Том второй",
            "price": 1240,
            "tags": ["комиксы"],
            "url": "https://www.labirint.ru/books/744320/",
            "image": "https://img4.labirint.ru/rc/c1b5ccf2fc15a72a72349dcd767a0980/220x340/books75/744320/cover.jpg?1585200359",
            "archived": 1
        },
        {
            "name": "Apple iPad 2019 32GB Wi-Fi Space Gray",
            "price": 26000,
            "tags": ["техника"],
            "url": "https://biggeek.ru/products/apple-ipad-2019-32gb-wi-fi-space-gray",
            "image": "https://cdn2.biggeek.ru/1/435/711c/9900-385ipad-wifi-select-space-201909_GEO_RU.png",
            "archived": 1,
        },
        {
            "name": "Lego Экстремальный внедорожник",
            "price": 12500,
            "tags": ["lego"],
            "url": "https://mir-kubikov.ru/lego/42099/",
            "image": "https://mir-kubikov.ru/upload/resize_cache/iblock/6b2/670_520_140cd750bba9870f18aada2478b24840a/6b23f2e4088abd8b6f802fa4e1792f92.jpg",
            "archived": 1,
        },
        {
            "name": "Lego Batmobile",
            "price": 20000,
            "image": "https://mir-kubikov.ru/upload/resize_cache/iblock/b2a/746_580_140cd750bba9870f18aada2478b24840a/b2af09393c7e0bc105372029af274a56.jpg",
            "tags": ["lego"],
            "url": "https://mir-kubikov.ru/lego/76139/",
            "archived": 1,
        },
        {
            "name": "Рюкзак Nomatic Travel Pack",
            "price": 21600,
            "image": "https://cdn.shopify.com/s/files/1/0745/1299/products/travel-pack_1024x1024.jpg?v=1588217895",
            "tags": ["полезное"],
            "url": "https://www.bagandwallet.ru/collection/nomatic/product/nomatic_travel_pack_kupit",
            "archived": 1,
        },
                {
            "name": "Техносвященники. Том первый",
            "price": 1400,
            "tags": ["комиксы"],
            "url": "https://www.labirint.ru/books/731757/",
            "image": "https://img3.labirint.ru/rc/9ee30ed65a26f742e7dac59db4abeba3/220x340/books74/731757/cover.jpg?1577273210",
            "archived": 1,
        },
    ]
}
